import { AmulProduct, PincodeLocation, ActivityLog, RestockEvent } from '../types/amul';

export const INITIAL_PRODUCTS: AmulProduct[] = [
  {
    id: 'amul-protein-lassi-plain',
    title: 'Amul High Protein Plain Lassi (200 mL | Pack of 30)',
    category: 'protein',
    flavor: 'Plain',
    imageUrl: 'https://shop.amul.com/s/62fa94df8c13af2e242eba16/66d15f3206e72f00e5bcef29/01-hero-image_multipack-30.png',
    description: '15g high-quality milk protein per pack with traditional rich flavor. Zero added sugar, rich in calcium and BCAAs.',
    nutrition: {
      proteinGrams: 15,
      calories: 110,
      carbsGrams: 8,
      fatGrams: 1.5,
      servingSize: '200ml pack',
    },
    defaultPrice: 750,
    isPopular: true,
    autoCartEnabled: true,
    variants: [
      {
        id: 'lassi-plain-30',
        name: 'Pack of 30 (200ml)',
        packSize: '200ml x 30',
        packCount: 30,
        price: 750,
        originalPrice: 750,
        isInStock: true,
        stockCount: 307,
        sku: 'AMUL-LASSI-PLAIN-30',
      },
    ],
  },
  {
    id: 'amul-whey-protein-32g',
    title: 'Amul Whey Protein Powder (Unflavoured 32g | Pack of 30)',
    category: 'protein',
    flavor: 'Natural',
    imageUrl: 'https://shop.amul.com/s/62fa94df8c13af2e242eba16/6523d269b4624b6c91f32572/01-hero-image_amul-whey-protein-960g.png',
    description: 'Pure 32g Whey protein isolate per sachet. Single-origin Indian dairy whey with supreme bioavailability.',
    nutrition: {
      proteinGrams: 32,
      calories: 140,
      carbsGrams: 2,
      fatGrams: 0.5,
      servingSize: '34g sachet',
    },
    defaultPrice: 1999,
    isPopular: true,
    autoCartEnabled: true,
    variants: [
      {
        id: 'whey-30',
        name: 'Pack of 30 Sachets (960g)',
        packSize: '32g x 30',
        packCount: 30,
        price: 1999,
        originalPrice: 1999,
        isInStock: true,
        stockCount: 52,
        sku: 'AMUL-WHEY-30',
      },
    ],
  },
  {
    id: 'amul-choco-whey-protein',
    title: 'Amul Chocolate Whey Protein (34g | Pack of 60 Sachets)',
    category: 'protein',
    flavor: 'Rich Chocolate',
    imageUrl: 'https://shop.amul.com/s/62fa94df8c13af2e242eba16/6a4e217e31d9dc76fdbd8ce5/01-hero-image_amul-whey-protein-204kg.png',
    description: '34g premium chocolate whey protein with natural cocoa extract and zero artificial sweeteners.',
    nutrition: {
      proteinGrams: 34,
      calories: 155,
      carbsGrams: 3,
      fatGrams: 1.0,
      servingSize: '34g sachet',
    },
    defaultPrice: 3899,
    isPopular: true,
    autoCartEnabled: true,
    variants: [
      {
        id: 'choco-whey-60',
        name: 'Pack of 60 Sachets (2.04kg)',
        packSize: '34g x 60',
        packCount: 60,
        price: 3899,
        originalPrice: 3899,
        isInStock: true,
        stockCount: 34,
        sku: 'AMUL-WHEY-CHOC-60',
      },
    ],
  },
  {
    id: 'amul-high-protein-paneer',
    title: 'Amul High Protein Paneer (400g | Pack of 2)',
    category: 'protein',
    flavor: 'Fresh Malai',
    imageUrl: 'https://shop.amul.com/s/62fa94df8c13af2e242eba16/671b30a3caec6f032c8154ed/01-hero-image_amul-high-protein-paneer-400g.png',
    description: '100g pure casein and whey protein per block. Made from ultra-filtered pasteurized skimmed milk.',
    nutrition: {
      proteinGrams: 50,
      calories: 280,
      carbsGrams: 6,
      fatGrams: 5.0,
      servingSize: '200g block',
    },
    defaultPrice: 170,
    isPopular: true,
    autoCartEnabled: true,
    variants: [
      {
        id: 'paneer-400',
        name: '400g x 2 Packs',
        packSize: '400g x 2',
        packCount: 2,
        price: 170,
        originalPrice: 170,
        isInStock: true,
        stockCount: 95,
        sku: 'AMUL-PANEER-50G',
      },
    ],
  },
  {
    id: 'amul-protein-buttermilk',
    title: 'Amul High Protein Buttermilk (200 mL | Pack of 30)',
    category: 'protein',
    flavor: 'Spiced Jeera',
    imageUrl: 'https://shop.amul.com/s/62fa94df8c13af2e242eba16/641a9c5dd94fc09d55a79318/01-hero-image_-multipack-30.png',
    description: '15g pure dairy protein with traditional Indian spices like cumin, ginger, and green chilli.',
    nutrition: {
      proteinGrams: 15,
      calories: 85,
      carbsGrams: 4,
      fatGrams: 0.8,
      servingSize: '200ml',
    },
    defaultPrice: 600,
    isPopular: true,
    autoCartEnabled: true,
    variants: [
      {
        id: 'buttermilk-30',
        name: '200ml x 30 Packs',
        packSize: '200ml x 30',
        packCount: 30,
        price: 600,
        originalPrice: 600,
        isInStock: true,
        stockCount: 180,
        sku: 'AMUL-CHAAS-15G',
      },
    ],
  },
];

export const INITIAL_PINCODES: PincodeLocation[] = [
  { pincode: '110044', label: 'South Delhi Hub', address: 'Okhla Phase 1, South Delhi', storeId: 'DEL_SOUTH_01', isDefault: true, serviceable: true },
  { pincode: '560001', label: 'Bengaluru Central', address: 'MG Road, Central Bengaluru', storeId: 'BLR_CENTRAL_01', isDefault: false, serviceable: true },
  { pincode: '400050', label: 'Mumbai Bandra', address: 'Bandra West, Mumbai Metro', storeId: 'BOM_WEST_02', isDefault: false, serviceable: true },
  { pincode: '122001', label: 'Gurugram Cyber City', address: 'DLF Cyber City, Gurugram', storeId: 'GGN_NORTH_01', isDefault: false, serviceable: true },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    type: 'restock',
    title: 'Drop Detected: Amul Protein Lassi (Rose)',
    description: '307 units detected in South Delhi Hub (110044)',
    timestamp: Date.now() - 1000 * 60 * 12,
    status: 'success',
    pincode: '110044',
  },
  {
    id: 'log-2',
    type: 'info',
    title: 'Radar Ping: Bengaluru Central (560001)',
    description: 'Checked 12 items. Whey Protein currently Out of Stock.',
    timestamp: Date.now() - 1000 * 60 * 25,
    status: 'info',
    pincode: '560001',
  },
];

export const MOCK_RESTOCK_EVENT: RestockEvent = {
  id: 'drop_evt_1',
  productId: 'amul-protein-lassi-plain',
  productName: 'Amul High Protein Plain Lassi (200 mL | Pack of 30)',
  variantName: '200ml x 30',
  unitsAdded: 307,
  timestamp: Date.now(),
  pincode: '110044',
  survivalDurationSecs: 180,
};
