import { AmulProduct, PincodeLocation, ActivityLog, RestockEvent } from '../types/amul';

export const INITIAL_PRODUCTS: AmulProduct[] = [
  {
    id: 'amul-protein-lassi-rose',
    title: 'Amul High Protein Lassi (Rose)',
    category: 'lassi',
    flavor: 'Rose',
    imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&q=80',
    description: '15g high-quality milk protein per pack with traditional rose flavor. Zero added sugar, rich in calcium and BCAAs.',
    nutrition: {
      proteinGrams: 15,
      calories: 110,
      carbsGrams: 8,
      fatGrams: 1.5,
      servingSize: '200ml pack',
    },
    defaultPrice: 750,
    isPopular: true,
    autoCartEnabled: true,
    variants: [
      {
        id: 'lassi-rose-30',
        name: 'Pack of 30 (200ml)',
        packSize: '200ml x 30',
        packCount: 30,
        price: 750,
        originalPrice: 750,
        isInStock: true,
        stockCount: 14,
        sku: 'AMUL-LASSI-ROSE-30',
      },
      {
        id: 'lassi-rose-8',
        name: 'Pack of 8 (200ml)',
        packSize: '200ml x 8',
        packCount: 8,
        price: 200,
        isInStock: false,
        stockCount: 0,
        sku: 'AMUL-LASSI-ROSE-8',
      },
      {
        id: 'lassi-rose-1',
        name: 'Single Pack (200ml)',
        packSize: '200ml',
        packCount: 1,
        price: 25,
        isInStock: true,
        stockCount: 8,
        sku: 'AMUL-LASSI-ROSE-1',
      },
    ],
  },
  {
    id: 'amul-protein-lassi-plain',
    title: 'Amul High Protein Lassi (Plain/Unsweetened)',
    category: 'lassi',
    flavor: 'Plain',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&q=80',
    description: 'Pure fermented dairy lassi packed with 15g protein. No sugar, no artificial flavors, pure probiotic goodness.',
    nutrition: {
      proteinGrams: 15,
      calories: 95,
      carbsGrams: 5,
      fatGrams: 1.2,
      servingSize: '200ml pack',
    },
    defaultPrice: 750,
    isPopular: true,
    autoCartEnabled: true,
    variants: [
      {
        id: 'lassi-plain-30',
        name: 'Pack of 30 (200ml)',
        packSize: '200ml x 30',
        packCount: 30,
        price: 750,
        isInStock: false,
        stockCount: 0,
        sku: 'AMUL-LASSI-PLAIN-30',
      },
      {
        id: 'lassi-plain-1',
        name: 'Single Pack (200ml)',
        packSize: '200ml',
        packCount: 1,
        price: 25,
        isInStock: false,
        stockCount: 0,
        sku: 'AMUL-LASSI-PLAIN-1',
      },
    ],
  },
  {
    id: 'amul-protein-buttermilk',
    title: 'Amul High Protein Buttermilk',
    category: 'buttermilk',
    flavor: 'Spiced Masala / Plain',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80',
    description: 'Refreshing traditional Indian Chaas fortified with 15g milk protein. Low calorie, cooling, and gut-friendly.',
    nutrition: {
      proteinGrams: 15,
      calories: 82,
      carbsGrams: 4,
      fatGrams: 0.8,
      servingSize: '200ml pack',
    },
    defaultPrice: 600,
    isPopular: false,
    autoCartEnabled: false,
    variants: [
      {
        id: 'bm-30',
        name: 'Pack of 30 (200ml)',
        packSize: '200ml x 30',
        packCount: 30,
        price: 600,
        isInStock: false,
        stockCount: 0,
        sku: 'AMUL-BM-30',
      },
      {
        id: 'bm-1',
        name: 'Single Pack (200ml)',
        packSize: '200ml',
        packCount: 1,
        price: 20,
        isInStock: false,
        stockCount: 0,
        sku: 'AMUL-BM-1',
      },
    ],
  },
  {
    id: 'amul-protein-whey-sachets',
    title: 'Amul High Protein Whey 32g Sachets',
    category: 'whey',
    flavor: 'Chocolate',
    imageUrl: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400&q=80',
    description: 'Instantized Whey Protein Concentrate with 24g pure protein and 5.5g BCAAs per 32g serving. Amul native milk whey.',
    nutrition: {
      proteinGrams: 24,
      calories: 130,
      carbsGrams: 3,
      fatGrams: 2,
      servingSize: '32g single sachet',
    },
    defaultPrice: 2100,
    isPopular: true,
    autoCartEnabled: true,
    variants: [
      {
        id: 'whey-30',
        name: 'Box of 30 Sachets (32g each)',
        packSize: '32g x 30 (960g)',
        packCount: 30,
        price: 2100,
        originalPrice: 2400,
        isInStock: true,
        stockCount: 6,
        sku: 'AMUL-WHEY-CHOCO-30',
      },
      {
        id: 'whey-10',
        name: 'Box of 10 Sachets (32g each)',
        packSize: '32g x 10',
        packCount: 10,
        price: 750,
        isInStock: false,
        stockCount: 0,
        sku: 'AMUL-WHEY-CHOCO-10',
      },
    ],
  },
  {
    id: 'amul-protein-paneer',
    title: 'Amul High Protein Fresh Paneer',
    category: 'paneer',
    flavor: 'Classic Fresh Dairy',
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80',
    description: 'Specially crafted ultra-filtered fresh paneer delivering a massive 25g protein per 100g with ultra-low fat content.',
    nutrition: {
      proteinGrams: 50,
      calories: 240,
      carbsGrams: 4,
      fatGrams: 3.5,
      servingSize: '200g slab',
    },
    defaultPrice: 95,
    isPopular: true,
    autoCartEnabled: false,
    variants: [
      {
        id: 'paneer-200g',
        name: '200g Fresh Vacuum Pack',
        packSize: '200g',
        packCount: 1,
        price: 95,
        isInStock: true,
        stockCount: 22,
        sku: 'AMUL-PANEER-HP-200',
      },
      {
        id: 'paneer-1kg',
        name: '1kg Bulk Block (5x200g)',
        packSize: '1kg (5 packs)',
        packCount: 5,
        price: 450,
        isInStock: false,
        stockCount: 0,
        sku: 'AMUL-PANEER-HP-1KG',
      },
    ],
  },
  {
    id: 'amul-protein-yogurt',
    title: 'Amul High Protein Greek Yogurt (Blueberry)',
    category: 'specialty',
    flavor: 'Blueberry',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&q=80',
    description: 'Thick strained dairy yogurt with real fruit preparation. 15g protein per cup. Zero trans fats.',
    nutrition: {
      proteinGrams: 15,
      calories: 120,
      carbsGrams: 10,
      fatGrams: 0.5,
      servingSize: '150g cup',
    },
    defaultPrice: 360,
    isPopular: false,
    autoCartEnabled: false,
    variants: [
      {
        id: 'yogurt-6',
        name: 'Pack of 6 Cups (150g)',
        packSize: '150g x 6',
        packCount: 6,
        price: 360,
        isInStock: false,
        stockCount: 0,
        sku: 'AMUL-YOGURT-BLUEBERRY-6',
      },
    ],
  },
];

export const INITIAL_PINCODES: PincodeLocation[] = [
  {
    pincode: '560034',
    label: 'Home',
    address: 'Koramangala 4th Block, Bengaluru, KA',
    storeId: 'BLR_CENTRAL_01',
    isDefault: true,
    distanceKm: 0,
    serviceable: true,
  },
  {
    pincode: '560066',
    label: 'Office',
    address: 'Whitefield Tech Park, Bengaluru, KA',
    storeId: 'BLR_EAST_04',
    isDefault: false,
    distanceKm: 4.8,
    serviceable: true,
  },
  {
    pincode: '560001',
    label: 'Gym',
    address: 'MG Road, Bengaluru, KA',
    storeId: 'BLR_CBD_02',
    isDefault: false,
    distanceKm: 3.2,
    serviceable: true,
  },
  {
    pincode: '110001',
    label: 'Delhi Central',
    address: 'Connaught Place, New Delhi, DL',
    storeId: 'DEL_CENTRAL_01',
    isDefault: false,
    distanceKm: 2150,
    serviceable: true,
  },
  {
    pincode: '400001',
    label: 'Mumbai Fort',
    address: 'Fort, Mumbai, MH',
    storeId: 'MUM_SOUTH_01',
    isDefault: false,
    distanceKm: 980,
    serviceable: true,
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    type: 'restock',
    title: 'Amul High Protein Lassi (Rose) Restocked',
    description: '14 units detected at Bengaluru Central (560034). Added to catalog.',
    timestamp: Date.now() - 1000 * 60 * 2, // 2 mins ago
    status: 'success',
    metadata: { productId: 'amul-protein-lassi-rose', pincode: '560034' },
  },
  {
    id: 'log-2',
    type: 'auto_cart',
    title: 'Headless Pre-Cart Locked in 240ms',
    description: 'Auto-cart reservation executed successfully for Pack of 30 Rose Lassi.',
    timestamp: Date.now() - 1000 * 60 * 2,
    status: 'success',
  },
  {
    id: 'log-3',
    type: 'heartbeat',
    title: 'Session Keeper Daemon Heartbeat',
    description: 'Pinged GET /api/v1/user/profile. Status 200 OK — Session valid for 48h.',
    timestamp: Date.now() - 1000 * 60 * 180, // 3 hours ago
    status: 'info',
  },
  {
    id: 'log-4',
    type: 'alert',
    title: 'High Protein Buttermilk Depleted',
    description: 'Batch of 500 units exhausted in 2 mins 45 secs at Koramangala Hub.',
    timestamp: Date.now() - 1000 * 60 * 60 * 24, // 1 day ago
    status: 'warning',
  },
];

export const MOCK_RESTOCK_ANALYTICS = {
  mostLikelyWindow: '11:15 AM – 12:30 PM',
  confidencePercent: 82,
  daysPattern: ['Tue', 'Thu', 'Sat'],
  averageSurvivalSeconds: 165, // 2 mins 45 secs
  fastestExhaustionSecs: 94,
  totalRestocksThisMonth: 19,
  lastRestockTimestamp: Date.now() - 1000 * 60 * 14,
  warehouseCluster: 'Mother Dairy Bengaluru / Whitefield Hub',
};
